<?php

/**
 * @file
 * Custom contexts.
 */

/**
 * Implements hook_context_plugins().
 */
function custom_context_context_plugins() {
  $plugins = array();
  $plugins['custom_context_context_condition_publish'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_context') . '/plugins',
      'file' => 'custom_context_context_condition_publish.inc',
      'class' => 'custom_context_context_condition_publish',
      'parent' => 'context_condition',
    ),
  );
  $plugins['custom_context_context_condition_expire'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_context') . '/plugins',
      'file' => 'custom_context_context_condition_expire.inc',
      'class' => 'custom_context_context_condition_expire',
      'parent' => 'custom_context_context_condition_publish',
    ),
  );
  $plugins['custom_context_context_condition_userpermission'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_context') . '/plugins',
      'file' => 'custom_context_context_condition_userpermission.inc',
      'class' => 'custom_context_context_condition_userpermission',
      'parent' => 'context_condition',
    ),
  );
  $plugins['custom_context_context_condition_timebased'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_context') . '/plugins',
      'file' => 'custom_context_context_condition_timebased.inc',
      'class' => 'custom_context_context_condition_timebased',
      'parent' => 'context_condition',
    ),
  );

  $plugins['custom_context_context_reaction_showmessage'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_context') .'/plugins',
      'file' => 'custom_context_context_reaction_showmessage.inc',
      'class' => 'custom_context_context_reaction_showmessage',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
} // custom_context_context_plugins

 /**
 * Implements hook_context_registry().
 */
function custom_context_context_registry() {
  return array(
    'conditions' => array(
      'publish' => array(
        'title' => t('Publish Date/Time'),
        'plugin' => 'custom_context_context_condition_publish',
      ),
      'expire' => array(
        'title' => t('Expire Date/Time'),
        'plugin' => 'custom_context_context_condition_expire',
      ),
      'userpermission' => array(
        'title' => t('User permission'),
        'plugin' => 'custom_context_context_condition_userpermission',
      ),
      'timebased' => array(
        'title' => t('Time based (hh:mm)'),
        'plugin' => 'custom_context_context_condition_timebased',
      ),
    ),
    'reactions' => array(
      'showmessage' => array(
        'title' => t('Show a message on the site.'),
        'plugin' => 'custom_context_context_reaction_showmessage',
      ),
    ),
  );
} // custom_context_context_registry

 /**
 * Implementation of hook_context_page_condition().
 */
function custom_context_context_page_condition() {
  $conditions = array(
    'publish',
    'expire',
    'userpermission',
    'timebased',
  );
  // Load the condition plugins and execute.
  foreach ($conditions as $condition) {
    if ($plugin = context_get_plugin('condition', $condition)) {
      $plugin->execute();
    } // if
  } // foreach
} // custom_context_context_page_condition

/**
 * Implements hook_context_page_reaction.
 */
function custom_context_context_page_reaction() {
  if ($plugin = context_get_plugin('reaction', 'showmessage')) {
    $plugin->execute();
  } // if
} // custom_context_context_page_reaction