<?php

/**
 * @file
 * Custom contexts.
 */

/**
 * Implements hook_context_plugins().
 */
function custom_context_context_plugins() {
  $plugins = array();
  $plugins['custom_context_context_condition_publish'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_context') . '/plugins',
      'file' => 'custom_context_context_condition_publish.inc',
      'class' => 'custom_context_context_condition_publish',
      'parent' => 'context_condition',
    ),
  );
  $plugins['custom_context_context_condition_expire'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_context') . '/plugins',
      'file' => 'custom_context_context_condition_expire.inc',
      'class' => 'custom_context_context_condition_expire',
      'parent' => 'custom_context_context_condition_publish',
    ),
  );
  $plugins['custom_context_context_condition_userpermission'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_context') . '/plugins',
      'file' => 'custom_context_context_condition_userpermission.inc',
      'class' => 'custom_context_context_condition_userpermission',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
} // custom_context_context_plugins

 /**
 * Implements hook_context_registry().
 */
function custom_context_context_registry() {
  return array(
    'conditions' => array(
      'publish' => array(
        'title' => t('Publish Date/Time'),
        'plugin' => 'custom_context_context_condition_publish',
      ),
      'expire' => array(
        'title' => t('Expire Date/Time'),
        'plugin' => 'custom_context_context_condition_expire',
      ),
      'userpermission' => array(
        'title' => t('User permission'),
        'plugin' => 'custom_context_context_condition_userpermission',
      ),
    ),
  );
} // custom_context_context_registry

 /**
 * Implementation of hook_context_page_condition().
 */
function custom_context_context_page_condition() {
  $conditions = array(
    'publish',
    'expire',
    'userpermission',
  );
  // Load the condition plugins and execute.
  foreach ($conditions as $condition) {
    if ($plugin = context_get_plugin('condition', $condition)) {
      $plugin->execute();
    } // if
  } // foreach
} // custom_context_context_page_condition
